//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinShop_Backstage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string orderId { get; set; }
        public string memberId { get; set; }
        public string cartId { get; set; }
        public int total { get; set; }
        public int paymentClass { get; set; }
        public string creditCard { get; set; }
        public string sendOption { get; set; }
        public string reci { get; set; }
        public int reciPhone { get; set; }
        public string reciAddress { get; set; }
        public System.DateTime date { get; set; }
        public string ps { get; set; }
    
        public virtual paymentClass paymentClass1 { get; set; }
        public virtual shoppingCart shoppingCart { get; set; }
    }
}
