//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinShop_frontdesk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mineshopEntities : DbContext
    {
        public mineshopEntities()
            : base("name=mineshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<level1Class> level1Class { get; set; }
        public virtual DbSet<level2Class> level2Class { get; set; }
        public virtual DbSet<level3Class> level3Class { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<paymentClass> paymentClass { get; set; }
        public virtual DbSet<pickingDetail> pickingDetail { get; set; }
        public virtual DbSet<pickingList> pickingList { get; set; }
        public virtual DbSet<quotation> quotation { get; set; }
        public virtual DbSet<saleInvoice> saleInvoice { get; set; }
        public virtual DbSet<ship> ship { get; set; }
        public virtual DbSet<shoppingCart> shoppingCart { get; set; }
        public virtual DbSet<shoppingDetail> shoppingDetail { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<status> status { get; set; }
    }
}
