//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinShop_frontdesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stock()
        {
            this.level2Class1 = new HashSet<level2Class>();
            this.level3Class1 = new HashSet<level3Class>();
            this.pickingDetail = new HashSet<pickingDetail>();
            this.quotation = new HashSet<quotation>();
            this.shoppingDetail = new HashSet<shoppingDetail>();
        }
    
        public string productId { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public string image { get; set; }
        public string level1Class { get; set; }
        public string level2Class { get; set; }
        public string level3Class { get; set; }
        public System.DateTime releaseDate { get; set; }
        public System.DateTime removalDate { get; set; }
        public int inventory { get; set; }
    
        public virtual level1Class level1Class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<level2Class> level2Class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<level3Class> level3Class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pickingDetail> pickingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quotation> quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shoppingDetail> shoppingDetail { get; set; }
    }
}
