//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinShop_frontdesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stock()
        {
            this.pickingDetail = new HashSet<pickingDetail>();
            this.quotation = new HashSet<quotation>();
            this.shoppingDetail = new HashSet<shoppingDetail>();
        }
    
        public string productId { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> specialoffer { get; set; }
        public string image { get; set; }
        public string level1Class { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<System.DateTime> removalDate { get; set; }
        public Nullable<int> inventory { get; set; }
        public string detailed { get; set; }
        public Nullable<int> click { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pickingDetail> pickingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<quotation> quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shoppingDetail> shoppingDetail { get; set; }
    }
}
